config/routes.rb
RecipezyV2::Application.routes.draw do

root :to => 'home#index'

resources :users, :tutorials, :ingredients
resources :recipes do
    collection do
      get :filter
      get :filterbytime
      post :add_item
    end
  end

resources :items, :only => [:index, :new, :create]

get '/login' => 'session#new'
post '/login' => 'session#create'
delete '/login' => 'session#destroy'

end

app/models/recipe.rb
# == Schema Information
#
# Table name: recipes
#
#  id             :integer          not null, primary key
#  title          :string(255)
#  key_ingredient :text
#  preptime       :text
#  cooktime       :text
#  image          :text
#  instructions   :text
#  servings       :integer
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#


class Recipe < ActiveRecord::Base
 attr_accessible :title, :key_ingredient, :preptime, :cooktime, :image, :instructions, :servings, :ingredient_ids
 belongs_to :user
 has_many :ingredients
 has_many :items
 has_and_belongs_to_many :tutorials

 def cost_per_serve
  cost_per_unit = self.ingredients.map(&:cost_per_unit)
  quantity = self.items.map(&:quantity)
  bought_quantity = self.ingredients.map(&:std_unit_quantity)
  items_quant = bought_quantity.zip(quantity).map{|b,q| q/b }
  items_cost = items_quant.zip(cost_per_unit).map{|a,b| a*b }
  total = items_cost.inject{|sum,x| sum + x } || 0
 end
 def total_time
  time = self.preptime.zip(self.cooktime).map{|p,c| (p.to_i)+(c.to_i) }
 end

end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def index
    @recipes = Recipe.order(:title)

    @ingredient = Ingredient.new
    @ingredients = @recipes.each.map(&:key_ingredient).uniq.sort
    preptime = @recipes.each.map(&:preptime)
    cooktime = @recipes.each.map(&:cooktime)
    @time = preptime.zip(cooktime).map{|p,c| (p.to_i)+(c.to_i) }
    @time = @time.uniq.sort
    respond_to do |format|
      format.html { render :index }
      format.js { render :index }
    end
 end
   def new
    @recipe = Recipe.new
  end
  def filter
    ingredient = params[:ingredient_select]
    @recipes = Recipe.where(:key_ingredient => ingredient)
  end
  def filterbytime
    time_select = params[:time_select]
    @recipes = Recipe.where(@recipes.total_time => time_select)
  end
  def create
    Recipe.create(params[:recipe])
    @recipes = Recipe.order(:title)
    respond_to do |format|
      format.html { redirect_to(recipes_path) }
      format.js { render :create }
    end
  end
  def show
    @recipe = Recipe.find(params[:id])
    @recipes = Recipe.all
    @tutorials = Tutorial.all
    @ingredients = Ingredient.all
    @ingredients.map!(&:name).sort
    # @ingredients = (@ingredient.each.map{|ing| ing.map{|a| a.name}}).flatten.sort
    @items = @recipe.items.each.map(&:recipe_note)
  end
  def edit
    @recipe = Recipe.find(params[:id])
    @item = Item.new
    respond_to do |format|
      format.html { }
      format.js { render :edit => @recipe }
    end
  end
  def update
    recipe = Recipe.find(params[:id])
    recipe.update_attributes(params[:recipe])
    redirect_to(recipe_path)
  end
  def destroy
    recipe = Recipe.find(params[:id])
    recipe.delete
    redirect_to(recipes_path)
  end
   def keyingredient
     render :json => found.where(:key_ingredient => params[:selected])
  end
  def add_item
    @item = Item.create(params[:item])
    @item.recipe_id = params[:recipe_id]
    @item.recipe_note = params[:recipe_note]
    @item.quantity = params[:quantity]
    @item.ingredient_id = params[:select_ingredient]
    @item.save
    Item.all.push(@item)
    respond_to do |format|
      format.html
      format.js
    end
    # @items = Item.where(@item.recipe_id => :recipe_id)
    # render :json => :items
  end
end

app/views/recipes/_form.html.haml
.large-5.columns
  = form_for @recipe do |f|
    = f.label :title
    = f.text_field :title, :autofocus => true
    = f.label :key_ingredient
    = f.text_field :key_ingredient
    = f.label :preptime
    = f.text_field :preptime
    = f.label :cooktime
    = f.text_field :cooktime
    = f.label :image
    = f.text_field :image
    = f.label :instructions
    = f.text_area :instructions
    = f.label :servings
    = f.text_field :servings
    = f.submit nil, :class => 'button radius tiny'
    .cancel_text.has-tip= link_to 'x', recipes_path, :remote => true, :id => 'cancel_recipe_form', :title => 'cancel recipe'
.large-7.columns

app/views/recipes/_items.html.haml
%h4= 'Ingredients'
- @items.each do |item|
  .eachitem= item
#totalcost= 'Total cost to make this recipe: ' + number_to_currency(@recipe.cost_per_serve)

app/views/recipes/_recipes.html.haml
- @recipes.each do |recipe|
  .panel.panelrecipe
    .singlerecipeheader= link_to "#{recipe.title}", recipe_path(recipe.id)
    %hr
    .singlerecipeimg= image_tag "#{recipe.image}"
    .prep-time-text= "Prep time"
    .prep-time-text= "Cook time"
    .prep-time-text= "Servings"
    %br
    .prep-time= "#{recipe.preptime}"
    .prep-time= "#{recipe.cooktime}"
    .prep-time= "#{recipe.servings}"
    .excerpt= "#{(recipe.instructions).truncate(200)}"
    =link_to( " Read More >>", recipe_path(recipe))

app/views/recipes/add_item.js.erb
$('#ingredient_list').empty();
$('#ingredient_list').append('<%=j render(:partial => 'items') %>');

app/views/recipes/cancel.js.erb
$('#new_recipe').show();
$('#recipes').show();
$('#recipes').children('<%=j render(:partial => 'recipes') %>').remove();

app/views/recipes/create.js.erb
$('#new_recipe').empty();
$('#recipes').show();
$('#recipes').append('<%=j render(:partial => 'recipes') %>');

app/views/recipes/edit.html.haml
= render(:partial => 'edit')

app/views/recipes/edit.js.erb
$('#new_recipe_btn').parent().parent().parent().parent().children().first().next().show();
$('#new_recipe').empty().append('<%=j render(:partial => 'edit') %>');
$('#recipes').hide();

app/views/recipes/filterbytime.js.erb
$('#new_recipe').empty();
$('#recipes').empty();
$('#recipes').append('<%=j render(:partial => 'recipes') %>');

app/views/recipes/index.html.haml
#recipenavbar
  .panel.recipenavpanel
    .row
      .small-12.columns
        = link_to('Add Recipe', new_recipe_path, :remote => 'true', :class => 'recipezybtn_recipeadd', :id => 'new_recipe_btn')
        = link_to('Browse All', recipes_path, :remote => 'true', :class => 'recipezybtn_recipenav', :id => 'browse_recipes')
        %hr
        #selectbytext= 'Or select by:'


        = form_tag filter_recipes_path, :method => :get, :remote => true do
          .selectfrom= select_tag 'ingredient_select', options_for_select(@ingredients.map{ |i| [i, i] })
          .recipezybtn_selectby= submit_tag 'Ingredient'

        = form_tag filterbytime_recipes_path, :method => :get, :remote => true do
          .selectfrom= select_tag 'time_select', options_for_select(@time.map{ |t| [t, t] })
          .recipezybtn_selectby= submit_tag 'Time'
          / = select_tag 'Cost', options_for_select(@costs.map{ |c| [c, c] })

.rowrecipes
  .small-7.columns
    #new_recipe

.rowrecipes
  #recipes

app/views/recipes/index.js.erb
$('#new_recipe_btn').parent().parent().parent().parent().children().first().next().show();
$('#new_recipe').empty().append('<%=j render(:partial => 'recipes') %>');
$('#recipes').show();

app/views/recipes/items.js.erb
$('#ingredient_list').empty();
$('#ingredient_list').append('<%=j render(:partial => 'items') %>');

app/views/recipes/new.js.erb
$('#new_recipe_btn').parent().parent().parent().parent().children().first().next().show();
$('#new_recipe').empty().append('<%=j render(:partial => 'form') %>');
$('#recipes').hide();

app/views/recipes/show.html.haml
.row
  .12-large.columns
    .panel.wholerecipe
      =link_to("<< Back to all recipes", recipes_path)
      %h4= "#{@recipe.title}"
      .keyingredient-text= "#{@recipe.key_ingredient}"
      / .minutes-text= "#{@recipe.preptime}"
      / .minutes-text= "#{@recipe.cooktime}"
      / .serves-text= "#{@recipe.servings}"
      != show_recipe_instructions(@recipe.instructions, @tutorials)
      =link_to 'Delete', @recipe, :method => :delete
      =link_to 'Edit', edit_recipe_path(@recipe), :method => :get

    #ingredient_list
      = render(:partial => 'items')

    #show_add_item_form= '+ Add an Ingredient'
    .4-large.columns
    #ingredient_form
      / =image_tag(@recipe.image, :class => 'showrecipeimg')
      #itemform.hide
        = form_tag add_item_recipes_path, :method => :post, :remote => true do
          = hidden_field_tag :recipe_id, @recipe.id
          = label_tag 'Select Ingredient'
          = select_tag 'select_ingredient', options_for_select(@ingredients.map{ |i| [i, i] })
          = label_tag 'How many units (ie ml, grams) does the recipe need?'
          = text_field_tag :quantity
          = label_tag 'Enter the ingredient as a line of text as it appears in your recipe'
          = text_field_tag :recipe_note
          .recipezybtn_additem= submit_tag 'Add Item to Recipe'
          #cancel_item_form
            .cancel_text= 'x'
          .clear