config/routes.rb
RecipezyV2::Application.routes.draw do

root :to => 'home#index'

resources :users, :tutorials, :ingredients
resources :recipes do
    collection do
      get :filter
      get :filterbytime
      post :add_item
    end
  end

resources :items, :only => [:index, :new, :create]

get '/login' => 'session#new'
post '/login' => 'session#create'
delete '/login' => 'session#destroy'

end

app/models/tutorial.rb
# == Schema Information
#
# Table name: tutorials
#
#  id          :integer          not null, primary key
#  name        :string(255)
#  description :text
#  video       :text
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Tutorial < ActiveRecord::Base
 attr_accessible :name, :description, :video
 has_and_belongs_to_many :recipes
end

app/controllers/tutorials_controller.rb
class TutorialsController < ApplicationController
  def index
    @tutorials = Tutorial.all
  end
  def new
    @tutorial = Tutorial.new
  end
  def create
    tutorial = Tutorial.create(params[:tutorial])
    redirect_to(tutorials_path)
  end
  def show
    @tutorial = Tutorial.find(params[:id])
  end
  def edit
    @tutorial = Tutorial.find(params[:id])
  end
  def update
    tutorial = Tutorial.find(params[:id])
    tutorial.update_attributes(params[:recipe])
    redirect_to(tutorial_path)
  end
  def destroy
    tutorial = Tutorial.find(params[:id])
    tutorial.delete
    redirect_to(tutorials)
  end
end

app/views/tutorials/index.html.haml
#new_tutorial

.row
  .panel
    .small-3.columns
      = link_to('Add Lesson', new_tutorial_path, :remote => 'true', :class => 'button radius', :id => 'new_tutorial_btn')
      = link_to('Browse All', tutorials_path, :remote => 'true', :class => 'button radius', :id => 'browse_tutorials')
    .small-9.columns

.row
  .small-7.columns
    #tutorials