config/routes.rb
RecipezyV2::Application.routes.draw do

root :to => 'home#index'

resources :users, :tutorials, :ingredients
resources :recipes do
    collection do
      get :filter
      get :filterbytime
      post :add_item
    end
  end

resources :items, :only => [:index, :new, :create]

get '/login' => 'session#new'
post '/login' => 'session#create'
delete '/login' => 'session#destroy'

end

app/views/layouts/_footer.html.erb
  <footer class="row">
    <div class="large-12 columns">
      <hr />
      <div class="row">
        <div class="large-6 columns">
          <p>&copy; Nicky Hughes Rails App 2013.</p>
        </div>
        <div class="large-6 columns">
          <ul class="inline-list right">
            <li><a href="http://nickyonrails.tumblr.com/" target='_blank'>Blog</a></li>
            <li><a href="http://nickyh.github.com/" target='_blank'>Portfolio</a></li>
            <li><a href="https://twitter.com/nichug00" target='_blank'>Twitter</a></li>
          </ul>
        </div>
      </div>
    </div>
  </footer>

app/views/layouts/_login.html.haml
.row
  .small-2.columns
  .panel.small-3.columns
    = form_tag '/login' do
      = label_tag 'email'
      = text_field_tag 'email', nil, :autofocus => true
      = label_tag 'password'
      = password_field_tag 'password'
      = submit_tag 'Sign in', :class => 'button radius'
    .cancel_text.has-tip= link_to 'x', recipes_path, :id => 'cancel_login_form', :title => 'cancel login'
.small-7.columns

app/views/layouts/_nav.html.erb
  <nav class="top-bar">
    <ul class="title-area">
      <div class='recipezy'><%= link_to (image_tag('recipezy.png')), root_path %></a></div>
    </ul>


    <section class="top-bar-section">
      <!-- Left Nav Section -->
      <ul class="left">
        <li class="has-dropdown">
          <% if @auth.present? %>
          <li><%= link_to('Logout', login_path, :method => :delete, :id => 'navtablog') %></li>
        <% else %>
          <li id='loginlink'><%= link_to('Login', login_path, :id => 'navtablog') %></li>
          <li class="divider"></li>
        <li><%= link_to('Sign Up!', new_user_path, :id => 'navtab') %></li>
        <% end %>
      </ul>

      <!-- Right Nav Section -->
      <ul class="right">

        <li class="has-dropdown">
           <% if @auth.present? %>

           <li><%= link_to("#{@auth.name}", users_path, :id => 'navtab') %></li>
           <li><%= link_to('Recipes', recipes_path, :id => 'navtab') %></li>
           <li><%= link_to('Ingredients', ingredients_path, :id => 'navtab') %></li>

        <li><%= link_to('Profile', user_path(@auth), :id => 'navtab') %></li>

        <li><%= link_to('Glossary', tutorials_path, :id => 'navtab') %></li>
         <% end %>

        </ul>
<div id='loginform' class='hide'>

</div>
    </section>
  </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!--[if IE 8]>         <html class="no-js lt-ie9" lang="en"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->
<html>
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width" />

  <title>Recipezy</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render :partial => 'layouts/nav' %>

<%= yield %>

<%= render :partial => 'layouts/footer' %>


  <script>
  $(document).foundation();
  </script>

</body>
</html>